FROM node:12

# not mandatory if you EXPORT a fixed port. See below.
ARG WEB_HTTP_PORT=8080

RUN apt-get -y update \
	&& apt-get install -y git

RUN npm install -g @vue/cli --verbose
RUN npm install -g cli-real-favicon --verbose

RUN apt-get autoremove -y \
    && apt-get autoclean -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/abecedaire

EXPOSE ${WEB_HTTP_PORT}
# Expose 8000 for vue-cli UI
EXPOSE 8000

USER node

# switch to npm if you chose it as package manager
CMD ["npm", "run", "serve"]