FROM node:12

# not mandatory if you EXPORT a fixed port. See below.
ARG WEB_HTTP_PORT=3000

RUN apt-get -y update \
	&& apt-get install -y git

RUN npm install -g @vue/cli --verbose

WORKDIR /usr/app/vue-cli-test

RUN apt-get autoremove -y \
    && apt-get autoclean -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Or just use EXPORT 8080
EXPOSE ${WEB_HTTP_PORT}
# If yout want use vue-cli UI you need to also EXPORT 8000 
EXPOSE 8000

USER node

# switch to npm if you chose it as package manager
CMD ["npm", "run", "serve"]